/**
 * Created by lenovo711 on 2015/9/17.
 */
var division = {
    "天津市": {
        "天津":"TIANJIN"
    },
    "重庆市": {
        "重庆市":"CHONGQING"
    },
    "上海市": {
        "上海":"SHANGHAI"
    },
    "北京市": {
        "北京市":"Beijing"
    },
    "四川省": {
        "巴中市":"bazhong",
        "成都市":"Chengdu",
        "崇州市":"congzhou",
        "达州市":"dazhou",
        "德阳市":"Deyang",
        "都江堰市":"dujiangyan",
        "峨眉山市":"emeishan",
        "广安市":"guangan",
        "广汉市":"Guanghan",
        "广元市":"guangyuan",
        "华蓥市":"huaying",
        "江油市":"jiangyou",
        "建阳市":"jianyang",
        "阆中市":"langzhong",
        "乐山市":"Leshan",
        "凉山彝族自治州":"Liangshan Yi Autonomous Prefecture",
        "泸州市":"Luzhou",
        "眉山市":"meishan",
        "绵阳市":"Mianyang",
        "绵竹市":"mianzhu",
        "南充市":"Nanchong",
        "内江市":"neijiang",
        "攀枝花市":"panzhihua",
        "彭州市":"pengzhou",
        "邛崃市":"qionglai",
        "什邡市":"shifang",
        "遂宁市":"suining",
        "阿坝藏族羌族自治州":"Tibetan and qiang Autonomous Prefecture of Aba",
        "甘孜藏族自治州":"Tibetan Autonomous Prefecture of Garzê",
        "万源市":"wanyuan",
        "西昌市":"Xichang",
        "雅安市":"yaan",
        "宜宾市":"yibing",
        "自贡市":"Zigong",
        "资阳市":"ziyang",
        "简阳":"Jiianyang"
    },
    "贵州省": {
        "安顺市":"Anshun",
        "毕节市":"bijie",
        "黔南布依族苗族自治州":"Buyi and Miao Autonomous Prefecture of QianNan",
        "黔西南布依族苗族自治州":"Buyi and Miao Autonomous Prefecture of QianXiNan",
        "赤水市":"chishui",
        "都匀市":"duyun",
        "福泉市":"fuquan",
        "贵阳市":"Guiyang",
        "凯里市":"kaili",
        "六盘水市":"liupanshui",
        "黔东南苗族侗族自治州":"Qiandongnan Miao and Dong Autonomous Prefecture",
        "清镇市":"qingzheng",
        "仁怀市":"renhuai",
        "铜仁市":"Tongren",
        "兴义市":"xingyi",
        "遵义市":"Zunyi"
    },
    "云南省": {
        "安宁市":"Anning",
        "保山市":"baoshan",
        "楚雄市":"chuxiong",
        "西双版纳傣族自治州":"Dai Autonomous Prefecture of Xishuangbanna/Sipsongpanna",
        "大理白族自治州":"Dali Bai Autonomous Prefecture",
        "大理市":"dali",
        "德宏傣族景颇族自治州":"Dehong  Autonomous Prefecture",
        "迪庆藏族自治州":"Diqing Tibetan Autonomous Prefecture",
        "个旧市":"gejiu",
        "红河哈尼族彝族自治州":"Hani-Yi Autonomous Prefecture of Honghe",
        "景洪市":"Jinghong",
        "开原市":"kaiyuan",
        "昆明市":"Kunming",
        "丽江市":"lijiang",
        "临沧市":"lincang",
        "芒市":"mangshi",
        "蒙自市":"mengzi",
        "弥勒市":"mile",
        "怒江傈僳族自治州":"Nujiang of the Lisu Autonomous Prefecture",
        "普洱市":"puer",
        "曲靖市":"qujing",
        "瑞丽市":"ruili",
        "楚雄彝族自治州":"weichu",
        "文山壮族苗族自治州":"Wenshan Zhuang and Miao Autonomous Prefecture",
        "文山市":"Wenshan",
        "宣威市":"xuanwei",
        "玉溪市":"yuxi",
        "昭通市":"zhaotong",
        "开远":"kaiyuan",
        "泸西":"Luxi"
    },
    "西藏自治区": {
        "安多县":"Amdo Zong",
        "昂仁县":"Angren County",
        "白朗县":"Bailang County",
        "班戈县":"Baingoin County",
        "巴青县":"Baqing",
        "八宿县":"Basu County",
        "边坝县":"Bianba County",
        "比如县":"Biru County",
        "波密县":"Bomi County",
        "普兰县":"Burang County",
        "察雅县":"Chaya County",
        "察隅县":"Chayu County",
        "措美县":"Comai County",
        "错那县":"Cona County",
        "措勤县":"Coqen County",
        "定结县":"Dingjie County",
        "丁青县":"dingqing",
        "定日县":"Dingri County",
        "岗巴县":"Gangba County",
        "噶尔县":"Gar County",
        "革吉县":"Gê'gya County",
        "改则县":"Gêrzê County",
        "工布江达县":"Gongbo'gvamda County",
        "贡嘎县":"Gongga",
        "贡觉县":"Gonjo County",
        "加查县":"Gyaca County",
        "江孜县":"Gyangzê County",
        "江达县":"Jiangda County",
        "吉隆县":"Jilong County",
        "康马县":"Kangma County",
        "昌都县":"Karuo District",
        "类乌齐县":"Leiwuqi County",
        "嘉黎县":"Lhari County",
        "拉萨市":"Lhasa",
        "拉孜县":"Lhazê County",
        "洛扎县":"Lhozhag County",
        "隆子县":"Lhünzê County",
        "洛隆县":"Luolong County",
        "米林县":"Mainling County",
        "芒康县":"Mangkang County",
        "墨脱县":"Mêdog County",
        "浪卡子县":"Nagarzê County",
        "那曲县":"Nagqu County",
        "那曲地区":"Nagqu Prefecture",
        "乃东县":"naidong",
        "南木林县":"Namling County",
        "朗县":"Nang County",
        "阿里地区":"Ngari Prefecture",
        "聂拉木县":"Nielamu County",
        "聂荣县":"Nyainrong County",
        "尼玛县":"Nyima County",
        "林芝县":"Nyingchi County",
        "林芝地区":"Nyingchi Prefecture",
        "昌都地区":"Qamdo City",
        "琼结县":"Qonggyai County",
        "曲松县":"Qusum County",
        "仁布县":"Renbu County",
        "日土县":"Rutog County",
        "萨嘎县":"Saga County",
        "萨迦县":"Sajia County",
        "桑日县":"Sangri County",
        "山南地区":"Shannan Prefecture",
        "日喀则市":"Shigatse City",
        "日喀则地区":"Shigatse Prefecture",
        "双湖县":"Shuanghu County",
        "索县":"Suo County",
        "申扎县":"Xainza County",
        "谢通门县":"Xietongmen County",
        "亚东县":"Yadong County",
        "札达县":"Zanda Zong",
        "扎囊县":"zhanang",
        "仲巴县":"Zhongba County",
        "左贡县":"Zuogong County"
    },
    "河南省": {
        "安阳市":"anyang",
        "长葛市":"changge",
        "登封市":"dengfeng",
        "邓州市":"dengzhou",
        "巩义市":"gongyi",
        "鹤壁市":"hebi",
        "辉县市":"huixian",
        "焦作市":"Jiaozuo",
        "济源市":"jiyuan",
        "开封市":"Kaifeng",
        "灵宝市":"lingboa",
        "林州市":"linzhou",
        "漯河市":"luohe",
        "洛阳市":"Luoyang",
        "孟州市":"mengzhou",
        "南阳市":"Nanyang",
        "平顶山市":"pingdingshan",
        "濮阳市":"puyang",
        "沁阳市":"qingyang",
        "汝州市":"ruzhou",
        "三门峡市":"sanmenxia",
        "商丘市":"Shangqiu",
        "卫辉市":"weihui",
        "武冈市":"wugang",
        "项城市":"xiangcheng",
        "新乡市":"Xingxiang",
        "新密市":"xinmi",
        "信阳市":"xinyang",
        "新郑市":"xinzheng",
        "许昌市":"xuchang",
        "偃师市":"yanshi",
        "义马市":"yima",
        "荥阳市":"yingyang",
        "永城市":"yongcheng",
        "禹州市":"yuzhou",
        "郑州市":"Zhengzhou",
        "周口市":"zhoukou",
        "驻马店市":"Zhumadian",
        "舞钢":"wugang"
    },
    "湖北省": {
        "安陆市":"anlu",
        "枣阳市":"caoyang",
        "赤壁市":"chibi",
        "当阳市":"dangyang",
        "丹江口市":"danjiangkou",
        "大冶市":"dazhi",
        "恩施土家族苗族自治州":"Enshi Tujia and Miao Autonomous Prefecture",
        "恩施市":"enshi",
        "鄂州市":"Ezhou",
        "广水市":"guangshui",
        "汉川市":"hanchuan",
        "武汉市":"Hankow",
        "洪湖市":"honghu",
        "黄冈市":"huanggang",
        "黄石市":"huangshi",
        "荆门市":"jingmen",
        "荆州市":"jingzhou",
        "老河口市":"laohekou",
        "利川市":"lichuan",
        "麻城市":"macheng",
        "潜江市":"qianjiang",
        "石首市":"shishou",
        "十堰市":"shiyan",
        "松滋市":"songzi",
        "随州市":"suizhou",
        "天门市":"tianmen",
        "武汉市":"Wuhan",
        "武穴市":"wuxue",
        "襄阳市":"xiangyang",
        "咸宁市":"xianning",
        "仙桃市":"xiantao",
        "孝感市":"Xiaogan",
        "宜昌市":"Yichang",
        "宜城市":"yicheng",
        "宜都市":"yidu",
        "应城市":"yingcheng",
        "枝江市":"zhijiang",
        "钟祥市":"zhongxiang",
        "襄樊":"Xiangfan"
    },
    "湖南省": {
        "常德市":"Changde",
        "常宁市":"changning",
        "长沙市":"Changsha",
        "郴州市":"chenzhou",
        "衡阳市":"Hengyang",
        "洪江市":"hongjiang",
        "怀化市":"huaihua",
        "界首市":"jieshou",
        "津市市":"jinshi",
        "耒阳市":"leiyanbg",
        "冷水江市":"lengshuijiang",
        "涟源市":"lianyuan",
        "醴陵市":"Liling",
        "临湘市":"linxiang",
        "浏阳市":"liuyang",
        "娄底市":"Loudi",
        "汨罗市":"miluo",
        "韶山市":"shaoshan",
        "邵阳市":"shaoyang",
        "武冈市":"wugang",
        "湘潭市":"Xiangtan",
        "湘西土家族苗族自治州":"Xiangxi Tujia and Miao Autonomous Prefecture",
        "湘乡市":"xiangxiang",
        "益阳市":"yiyang",
        "永州市":"Yongzhou",
        "沅江市":"yuanjiang",
        "岳阳市":"Yueyang",
        "张家界市":"zhangjiajie",
        "株洲市":"Zhuzhou",
        "资兴市":"zixing",
        "界首":"jieshou"
    },
    "广东省": {
        "广州市":"Canton",
        "潮州市":"chaozhou",
        "从化市":"conghua",
        "东莞市":"Dongguan",
        "恩平市":"enping",
        "佛山市":"Foshan",
        "高要市":"Gaoyao",
        "高州市":"gaozhou",
        "广州市":"Guangzhou",
        "鹤山市":"Heshan",
        "河源市":"Heyuan",
        "化州市":"huazhou",
        "惠州市":"Huiyang",
        "惠州市":"Huizhou",
        "江门市":"Jiangmen",
        "揭阳市":"jieyang",
        "普宁市":"jinning",
        "开平市":"Kaiping",
        "乐昌市":"lechang",
        "雷州市":"leizhou",
        "廉江市":"lianjiang",
        "连州市":"lianzhou",
        "陆丰市":"Lufeng",
        "罗定市":"luoding",
        "茂名市":"maoming",
        "梅州市":"Meizhou",
        "南雄市":"nanxiong",
        "清远市":"qingyuan",
        "汕头市":"Shantou",
        "汕尾市":"Shanwei",
        "韶关市":"Shaoguan",
        "深圳市":"Shenzhen",
        "四会市":"sihui",
        "台山市":"taishan",
        "湛江市":"Tsamkong",
        "吴川市":"Wu Chong Kou",
        "兴宁市":"xingning",
        "新沂市":"xinyi",
        "阳春市":"Yangchun",
        "阳江市":"Yangjiang",
        "英德市":"Yingde",
        "云浮市":"yunfu",
        "增城市":"Zengcheng",
        "湛江市":"Zhanjiang",
        "肇庆市":"Zhaoqing",
        "中山市":"Zhongshan",
        "珠海市":"Zhuhai",
        "信宜":"xinyi"
    },
    "广西壮族自治区": {
        "百色市":"baise",
        "北海市":"Beihai",
        "北流市":"beiliu",
        "岑溪市":"cengxi",
        "崇左市":"congzuo",
        "东兴市":"Dongxing",
        "防城港市":"fangchenggang",
        "贵港市":"guigang",
        "桂林市":"Guilin",
        "桂平市":"guiping",
        "河池市":"hechi",
        "鹤山市":"heshan",
        "贺州市":"hezhou",
        "来宾市":"laibing",
        "柳州市":"Liuzhou",
        "南宁市":"Nanning",
        "萍乡市":"pingxiang",
        "钦州市":"Qinzhou",
        "梧州市":"Wuzhou",
        "宜州市":"yizhou",
        "玉林市":"Yulin",
        "合山":"heshan",
        "萍乡":"pingxiang"
    },
    "陕西省": {
        "安康市":"ankang",
        "宝鸡市":"Baoji",
        "韩城市":"hancheng",
        "汉中市":"hanzhong",
        "华阴市":"huayin",
        "商洛市":"shangluo",
        "铜川市":"tongchuan",
        "渭南市":"weinan",
        "西安市":"Xi An",
        "咸阳市":"xianyang",
        "兴平市":"xingping",
        "延安市":"yanan",
        "玉林市":"Yulin",
        "榆林":"Yulin"
    },
    "甘肃省": {
        "白银市":"baiyin",
        "定西市":"dingxi",
        "敦煌市":"dunhuang",
        "合作市":"hezuo",
        "嘉峪关市":"jiayuguan",
        "金昌市":"jinchang",
        "酒泉市":"Jiuquan",
        "兰州市":"Lanzhou",
        "临夏回族自治州":"Linxia Hui Autonomous Prefecture",
        "临夏市":"linxia",
        "陇南市":"longnan",
        "平凉市":"pingliang",
        "沁阳市":"qingyang",
        "天水市":"tianshui",
        "甘南藏族自治州":"Tibetan Autonomous Prefecture of Ganan",
        "武威市":"wuwei",
        "玉门市":"yumen",
        "张掖市":"zhangye",
        "庆阳":"qingyang"
    },
    "青海省": {
        "德令哈市":"Delhi",
        "格尔木市":"Golmud",
        "海东市":"haidong",
        "海西蒙古族藏族自治州":"Haixi Mongolian and Tibetan Autonomous Prefecture",
        "果洛藏族自治州":"Tibetan Autonomous Prefecture of Guoluo",
        "海北藏族自治州":"Tibetan Autonomous Prefecture of Haibei",
        "海南藏族自治州":"Tibetan Autonomous Prefecture of Hainan",
        "黄南藏族自治州":"Tibetan Autonomous Prefecture of Huangnan",
        "玉树藏族自治州":"Tibetan Autonomous Prefecture of Yushu",
        "西宁市":"xining",
        "榆树市":"yushu"
    },
    "宁夏回族自治区": {
        "固原市":"guyuan",
        "灵武市":"lingwu",
        "青铜峡市":"qingtongxia",
        "石嘴山市":"shizuishan",
        "吴忠市":"wuzhong",
        "银川市":"Yinchuan",
        "中卫市":"zhongwei"
    },
    "新疆维吾尔自治区": {
        "阿拉尔市":"Alaer City",
        "阿拉山口市":"Alatawshankou",
        "阿勒泰地区":"Altay Prefecture",
        "阿勒泰市":"Altay",
        "阿图什市":"Atushi",
        "阿瓦提县":"Awat County",
        "巴楚县":"bachu",
        "白城市":"baicheng",
        "博乐市":"bole",
        "博尔塔拉蒙古自治州":"Bortala Mongol Autonomous Prefecture",
        "布尔津县":"Burqin County",
        "昌吉回族自治州":"Changji hui autonomous prefecture",
        "昌吉市":"changji",
        "额敏县":"Emin",
        "福海县":"fuhai",
        "阜康市":"fukang",
        "富蕴县":"Fuyun County",
        "哈巴河县":"Habahe County",
        "哈密地区":"Hami Prefecture",
        "哈密市":"Hami",
        "和田县":"Hotan County",
        "和田地区":"Hotan Prefecture",
        "和田市":"Hotan",
        "伊犁哈萨克自治州":"Ili Kazak Autonomous Prefecture",
        "吉木乃县":"Jeminay County",
        "伽师县":"Jiashi County",
        "柯坪县":"Kalpin County",
        "克拉玛依市":"Karamay",
        "喀什地区":"Kashi Prefecture",
        "喀什市":"Kashi",
        "巴里坤哈萨克自治县":"Kazak Autonomous County of Barkol",
        "克孜勒苏柯尔克孜自治州":"Kizilsu Kirghiz Autonomous Prefecture",
        "库尔勒市":"Korla",
        "奎屯市":"kuitun",
        "库车县":"Kuqa County",
        "洛浦县":"Lop County",
        "麦盖提县":"Markit County",
        "民丰县":"Minfeng",
        "和布克赛尔蒙古自治县":"Mongolian Autonomous County of Hoboksar",
        "巴音郭楞蒙古自治州":"Mongolian Autonomous Prefecture of Bayingolin",
        "墨玉县":"Moyu County",
        "皮山县":"Pishan County",
        "青河县":"qinghe",
        "策勒县":"Qira County",
        "莎车县":"Shache County",
        "鄯善县":"shanshan",
        "沙雅县":"shaya",
        "石河子市":"shihezi",
        "疏附县":"Shufu County",
        "沙湾县":"shwan",
        "塔城地区":"Tacheng Prefecture",
        "塔城市":"tacheng",
        "塔什库尔干塔吉克自治县":"Tajik Autonomous County of Taxkorgan",
        "托克逊县":"Toksun County",
        "托里县":"Toli",
        "图木舒克市":"Tumu Shuker",
        "吐鲁番市":"Turpan",
        "吐鲁番地区":"Turpan Prefecture",
        "乌鲁木齐市":"ürümqi",
        "温宿县":"wensu",
        "五家渠市":"wujianqu",
        "乌什县":"wushi",
        "乌苏市":"wusu",
        "新和县":"xinhe",
        "叶城县":"Yecheng County",
        "英吉沙县":"Yengisar",
        "伊宁市":"Yining",
        "义乌市":"yiwu",
        "岳普湖县":"Yuepuhu",
        "裕民县":"yumin",
        "于田县":"Yutian",
        "泽普县":"Zepu County",
        "博乐":"bole",
        "库尔勒":"Korla",
        "阿克苏":"Aksu",
        "阿图什":"Atushi",
        "喀什":"Kashi",
        "和田":"Hotan",
        "伊宁":"Yining",
        "奎屯":"kuitun",
        "塔城":"tacheng",
        "乌苏":"wusu",
        "阿尔泰":"Altay",
        "石河子":"shihezi",
        "阿拉尔":"Alaer City",
        "图木舒克":"Tumu Shuker",
        "五家渠":"wujianqu"
    },
    "河北省": {
        "安国市":"anguo",
        "保定市":"Baoding",
        "霸州市":"bazhou",
        "泊头市":"botou",
        "沧州市":"Cangzhou",
        "承德市":"Chengde",
        "秦皇岛市":"Chingwantao",
        "定州市":"dingzhou",
        "高碑店市":"gaobeidian",
        "藁城市":"gaocheng",
        "邯郸市":"Handan",
        "河间市":"hejian",
        "衡水市":"hengshui",
        "黄骅市":"Huanghua",
        "晋州市":"jinzhou",
        "冀州市":"jizhou",
        "廊坊市":"Langfang",
        "鹿泉市":"luquan",
        "南宫市":"nangong",
        "迁安市":"qianan",
        "秦皇岛市":"Qinhuangdao",
        "任丘市":"renqiu",
        "三河市":"sanhe",
        "沙河市":"Shahe",
        "深州市":"shenzhou",
        "石家庄市":"shijiazhuang",
        "唐山市":"Tangshan",
        "武安市":"wuan",
        "邢台市":"xingtai",
        "辛集市":"Xinji",
        "新乐市":"xinle",
        "张家口市":"Zhangjiakou",
        "涿州市":"Zhuozhou",
        "遵化市":"zunhua"
    },
    "山西省": {
        "长治市":"Changzhi",
        "大同市":"Datong",
        "汾阳市":"fenyang",
        "高平市":"gaoping",
        "古交市":"Gujiao",
        "河津市":"hejin",
        "侯马市":"houma",
        "霍州市":"huozhou",
        "介休市":"Jiexiu",
        "晋城市":"jincheng",
        "晋中市":"Jinzhong",
        "临汾市":"linfen",
        "潞城市":"lucheng",
        "吕梁市":"lvliang",
        "朔州市":"shuozhou",
        "太原市":"Taiyuan",
        "孝义市":"xiaoyi",
        "忻州市":"xinzhou",
        "阳泉市":"yangquan",
        "永济市":"Yongji",
        "原平市":"yuanping",
        "运城市":"Yuncheng"
    },
    "内蒙古自治区": {
        "阿拉善左旗":"Alxa Left Banner",
        "阿巴嘎旗":"Abag Banner",
        "阿拉善盟":"Alxa League",
        "阿拉善右旗":"Alxa Right Banner",
        "敖汉旗":"Aohan",
        "阿鲁科尔沁旗":"Ar Horqin Banner",
        "阿尔山市":"Arshaan",
        "阿荣旗":"Arun Banner",
        "巴林左旗":"Bairin Left Banner",
        "巴林右旗":"Bairin Right Banner",
        "包头市":"Baotou",
        "巴彦淖尔市":"Bayan Nur",
        "镶黄旗":"Boarder Yellow Banner",
        "察哈尔右翼后旗":"Chahar Right Back Banner",
        "察哈尔右翼前旗":"Chahar Right Front Banner",
        "察哈尔右翼中旗":"Chahar Right Middle Banner",
        "赤峰市":"Chifeng",
        "达拉特旗":"Dalad Banner",
        "达尔罕茂明安联合旗":"Darhan Muminggan Joint Banner",
        "莫力达瓦达斡尔族自治旗":"Daur Autonomous Banner of Morin Dawa",
        "额尔古纳市":"eerguna",
        "伊金霍洛旗":"Ejin Horo Banner",
        "二连浩特市":"Erenhot",
        "鄂温克族自治旗":"Ewenki Autonomous Banner",
        "丰镇市":"fengzhen",
        "根河市":"Genhe City",
        "杭锦旗":"Hanggin Banner",
        "杭锦后旗":"Hanggin Rear Banner",
        "喀喇沁旗":"Harqin Banner",
        "克什克腾旗":"Hexigten Banner",
        "兴安盟":"Hinggan League",
        "呼和浩特市":"Hohhot",
        "霍林郭勒市":"Holingola",
        "科尔沁左翼中旗":"Horqin Left Wing Middle Banner",
        "科尔沁左翼后旗":"Horqin Left Wing Rear Banner",
        "科尔沁右翼前旗":"Horqin Right Wing Front Banner",
        "科尔沁右翼中旗":"Horqin Right Wing Middle Banner",
        "呼伦贝尔市":"Hulun Buir",
        "库伦旗":"Hure Banner",
        "扎赉特旗":"Jalaid Banner",
        "扎鲁特旗":"Jarud Banner",
        "准格尔旗":"Jungar Banner",
        "满洲里市":"Manzhouli",
        "额济纳旗":"mesozoic-cenozoic",
        "奈曼旗":"Naiman Banner",
        "翁牛特旗":"Ongniud Bannar",
        "鄂尔多斯市":"Ordos",
        "鄂伦春自治旗":"Oroqen Autonomous Banner",
        "鄂托克旗":"Otog Banner",
        "鄂托克前旗":"Otog Front Banner",
        "陈巴尔虎旗":"Prairie Chenbarhu banner",
        "四子王旗":"Siziwang Banner",
        "苏尼特左旗":"Sonid Left Banner",
        "苏尼特右旗":"Sonid Right Banner",
        "太仆寺旗":"Taibus Banner",
        "通辽市":"Tongliao",
        "土默特左旗":"Tumd Left Banner",
        "土默特右旗":"Tumd Right Banner",
        "乌兰浩特市":"Ulan Hot",
        "乌兰察布市":"Ulanqab",
        "西乌珠穆沁旗":"West Ujimqin banner",
        "乌海市":"Wuhai",
        "乌拉特后旗":"Wulatehou Qi",
        "乌拉特前旗":"Wulateqian Qi",
        "乌拉特中旗":"Wulatezhong Qi",
        "乌审旗":"Wushen County",
        "锡林浩特市":"xilin hot",
        "锡林郭勒盟":"Xilingol League",
        "新巴尔虎左旗":"Xin Barag Left Banner",
        "新巴尔虎右旗":"Xin Barag Right Banner",
        "牙克石市":"Yakeshi",
        "扎兰屯市":"zhalantun",
        "正蓝旗":"Zhenglan Banner",
        "正镶白旗":"Zhengxiangbai Banner"
    },
    "江苏省": {
        "张家港市":"Changjiagang",
        "常熟市":"changshu",
        "常州市":"changzhou",
        "镇江市":"Chinkiang",
        "大丰市":"dafeng",
        "丹阳市":"danyang",
        "东台市":"dongtai",
        "高邮市":"gaoyou",
        "海门市":"haimen",
        "淮安市":"huaian",
        "江阴市":"Jiangyin",
        "靖江市":"Jingjiang",
        "金坛市":"jintai",
        "句容市":"jurong",
        "昆山市":"kushan",
        "连云港市":"Lianyungang",
        "南京市":"Nanjing",
        "南通市":"Nantong",
        "邳州市":"pizhou",
        "启东市":"qidong",
        "如皋市":"rugao",
        "宿迁市":"suqian",
        "溧阳市":"suyang",
        "苏州市":"Suzhou",
        "太仓市":"taicang",
        "泰兴市":"Taixing",
        "泰州市":"Taizhou",
        "无锡市":"Wuxi",
        "兴化市":"xinghua",
        "新沂市":"xinyi",
        "徐州市":"Xuzhou",
        "盐城市":"Yancheng",
        "扬中市":"yangzhong",
        "扬州市":"Yangzhou",
        "宜兴市":"Yixing",
        "仪征市":"Yizheng",
        "张家港市":"Zhangjiagang",
        "镇江市":"Zhenjiang",
        "吴江":"Wujiang",
        "通州":"Tongzhou",
        "江都":"Jiangdu",
        "姜堰":"Jiangyan"
    },
    "浙江省": {
        "嵊州市":"chengzhou",
        "慈溪市":"Cixi",
        "东阳市":"dongyang",
        "奉化市":"fenghua",
        "阜阳市":"fuyang",
        "海宁市":"Haining",
        "杭州市":"Hangchow",
        "杭州市":"Hangzhou",
        "湖州市":"Huzhou",
        "建德市":"jiande",
        "江山市":"jiangshan",
        "嘉兴市":"Jiaxing",
        "金华市":"jinhua",
        "兰溪市":"Lanxi",
        "临安市":"Lin'an",
        "凌海市":"Linhai",
        "丽水市":"Lishui",
        "龙泉市":"longquan",
        "宁波市":"Ningbo",
        "平湖市":"Pinghu",
        "衢州市":"Quzhou",
        "瑞安市":"ruian",
        "上虞市":"shangyu",
        "绍兴市":"shaoxing",
        "泰州市":"taizhou",
        "桐乡市":"Tongxiang",
        "温岭市":"Wenlin",
        "温州市":"Wenzhou",
        "义乌市":"Yiwu",
        "永康市":"yongkang",
        "乐清市":"Yueqing",
        "余姚市":"Yuyao",
        "舟山市":"Zhoushan",
        "诸暨市":"Zhuji",
        "富阳":"fuyang",
        "台州":"taizhou",
        "临海":"Linhai"
    },
    "安徽省": {
        "安庆市":"Anqing",
        "蚌埠市":"Bengbu",
        "亳州市":"bozhou",
        "巢湖市":"Chaohu",
        "池州市":"chizhou",
        "滁州市":"Chuzhou",
        "阜阳市":"fuyang",
        "合肥市":"Hefei",
        "淮北市":"Huaibei",
        "淮南市":"huainan",
        "黄山市":"Huangshan",
        "界首市":"jieshou",
        "六安市":"Luan",
        "马鞍山市":"Maanshan",
        "明光市":"mingguang",
        "宁国市":"ningguo",
        "天长市":"tianchang",
        "桐城市":"tongcheng",
        "铜陵市":"Tongling",
        "芜湖市":"Wuhu",
        "宣城市":"xuancheng",
        "宿州":"suzhou"
    },
    "福建省": {
        "长乐市":"Changle",
        "福州市":"Foochow",
        "福安市":"fuan",
        "福鼎市":"fuding",
        "福清市":"fuqing",
        "抚州市":"Fuzhou",
        "建瓯市":"jianou",
        "建阳市":"jianyang",
        "晋江市":"Jinjiang",
        "龙海市":"Longhai",
        "龙岩市":"longyan",
        "南安市":"Nan an",
        "南平市":"nanping",
        "宁德市":"ningde",
        "莆田市":"Putian",
        "泉州市":"Quanzhou",
        "三明市":"sanming",
        "邵武市":"shaowu",
        "石狮市":"shishi",
        "厦门市":"Xiamen",
        "永安市":"yongan",
        "漳平市":"zhangping",
        "漳州市":"Zhangzhou",
        "武夷山市":"wuyishan"
    },
    "江西省": {
        "德兴市":"dexing",
        "凤城市":"fengcheng",
        "抚州市":"fuzhou",
        "赣州市":"Ganzhou",
        "高安市":"gaoan",
        "共青城市":"gongqingcheng",
        "贵溪市":"guixi",
        "吉安市":"jian",
        "景德镇市":"Jingdezhen",
        "井冈山市":"jinggangshan",
        "九江市":"Jiujiang",
        "乐平市":"Leping",
        "南昌市":"Nanchang",
        "南康市":"nankang",
        "萍乡市":"Pingxiang",
        "瑞昌市":"ruichang",
        "瑞金市":"ruijin",
        "上饶市":"shangrao",
        "新余市":"xinyu",
        "伊春市":"yichun",
        "鹰潭市":"yingtan",
        "樟树市":"zhangshu",
        "宜春":"yichun",
        "丰城":"fengcheng"

    },
    "山东省": {
        "安丘市":"Anqiu",
        "滨州市":"Binzhou",
        "昌邑市":"changyi",
        "烟台市":"Chefoo",
        "德州市":"Dezhou",
        "东营市":"dongying",
        "肥城市":"feicheng",
        "高密市":"gaomi",
        "海阳市":"haiyang",
        "菏泽市":"Heze",
        "胶州市":"Jiaozhou",
        "即墨市":"Jimo",
        "济南市":"Jinan",
        "济宁市":"Jining",
        "莱芜市":"Laiwu",
        "莱西市":"laixi",
        "莱阳市":"Laiyang",
        "莱州市":"laizhou",
        "乐陵市":"leling",
        "聊城市":"liaocheng",
        "临清市":"linqing",
        "临沂市":"Linyi",
        "龙口市":"longkou",
        "蓬莱市":"penglai",
        "平度市":"pingdu",
        "青岛市":"Qingdao",
        "青州市":"qingzhou",
        "曲阜市":"qufu",
        "日照市":"Rizhao",
        "荣成市":"rongcheng",
        "乳山市":"rushan",
        "寿光市":"shouguang",
        "泰安市":"taian",
        "滕州市":"tengzhou",
        "潍坊市":"Weifang",
        "威海市":"Weihai",
        "文登市":"wendeng",
        "新泰市":"xintai",
        "栖霞市":"xixia",
        "烟台市":"Yantai",
        "兖州市":"yanzhou",
        "禹城市":"yucheng",
        "枣庄市":"zaozhuang",
        "章丘市":"zhangqiu",
        "招远市":"zhaoyuan",
        "诸城市":"Zhucheng",
        "淄博市":"Zibo",
        "邹城市":"zoucheng",
        "胶南":"Jiaonan"
    },
    "辽宁省": {
        "鞍山市":"Anshan",
        "北票市":"beipiao",
        "北镇市":"beizheng",
        "本溪市":"Benxi",
        "朝阳市":"chaoyang city",
        "大连市":"Dalian",
        "丹东市":"dandong",
        "大石桥市":"dashiqiao",
        "灯塔市":"dengta",
        "调兵山市":"diaobingshan",
        "东港市":"Donggang",
        "凤城市":"fengcheng",
        "抚顺市":"Fushun",
        "阜新市":"Fuxin",
        "盖州市":"gaizhou",
        "海城市":"Haicheng",
        "葫芦岛市":"huludao",
        "晋州市":"jinzhou",
        "开原市":"kaiyuan",
        "辽阳市":"Liaoyang",
        "凌海市":"linhai",
        "凌源市":"linyuan",
        "盘锦市":"panjin",
        "普兰店市":"pulandian",
        "沈阳市":"Shenyang",
        "铁岭市":"tieling",
        "瓦房店市":"Wafangdian",
        "兴城市":"xingcheng",
        "新民市":"xinmin",
        "营口市":"Yingkou",
        "庄河市":"zhuanghe",
        "锦州":"Jinzhou"
    },
    "吉林省": {
        "白城市":"Baicheng",
        "白山市":"baishan",
        "长春市":"Changchun",
        "大安市":"daan",
        "德惠市":"dehui",
        "敦化市":"dunhua",
        "扶余市":"fuyu",
        "和龙市":"helong",
        "桦甸市":"huadian",
        "珲春市":"Hunchun",
        "集安市":"Ji'an",
        "蛟河市":"jiaohe",
        "吉林市":"Jilin",
        "九台市":"jiutai",
        "辽源市":"liaoyuan",
        "临江市":"linjiang",
        "龙井市":"longjing",
        "梅河口市":"meihekou",
        "磐石市":"panshi",
        "双辽市":"shuangliao",
        "舒兰市":"shulan",
        "四平市":"siping",
        "松原市":"songyuan",
        "洮南市":"taonan",
        "通化市":"Tonghua",
        "图们市":"Tumen",
        "延边朝鲜族自治州":"Yanbian Korean Autonomous Prefecture",
        "延吉市":"Yanji",
        "榆树市":"yushu",
        "公主岭市":"Gongzhuling"
    },
    "黑龙江省": {
        "安达市":"anda",
        "北安市":"beian",
        "大庆市":"Daqing",
        "大兴安岭地区":"DaXingAnLing",
        "富锦市":"fujing",
        "海林市":"hailing",
        "海伦市":"hailun",
        "哈尔滨市":"Harbin",
        "鹤岗市":"hegang",
        "黑河市":"Heihe",
        "虎林市":"hulin",
        "呼玛县":"huma",
        "佳木斯市":"Jiamusi",
        "鸡西市":"jixi",
        "密山市":"mishan",
        "漠河县":"mohe",
        "牡丹江市":"Mudanjiang",
        "穆棱市":"muling",
        "讷河市":"nahe",
        "宁安市":"Ning'an",
        "齐齐哈尔市":"Qiqihar",
        "七台河市":"qitaihe",
        "尚志市":"shangzhi",
        "双城市":"shuangcheng",
        "双鸭山市":"shuangyashan",
        "绥芬河市":"suifenhe",
        "绥化市":"suihua",
        "塔河县":"tahe",
        "铁力市":"Tieli",
        "同江市":"tongjiang",
        "五常市":"wuchang",
        "五大连池市":"wudalianchi",
        "伊春市":"yichun",
        "肇东市":"Zhaodong",
        "漠河":"Mohe"
    },
    "海南省": {
        "儋州市":"Danzhou",
        "东方市":"dongfang",
        "海口市":"Haikou",
        "南沙群岛":"nansha",
        "琼海市":"Qionghai",
        "三亚市":"Sanya",
        "万宁市":"Wanning",
        "文昌市":"Wenchang",
        "五指山市":"wuzhishan",
        "西沙群岛":"xisha",
        "中沙群岛的岛礁及其海域":"zhongshaqundao"
    },
    "其他":{"香港":"","澳门":"MACAO","台湾":""}
};
